<?php

namespace Tuezy\Kernels;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use Tuezy\Kernels\Exceptions\NotSupportedException;

class AppConsoleKernel extends ConsoleKernel
{
    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        // $schedule->command('inspire')->hourly();
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(MODULES.'Commands');
    }

    public function handle($input, $output = null)
    {
        if($input->getFirstArgument() == 'serve'){
            throw new NotSupportedException("Not support");
        }
        return parent::handle($input, $output); // TODO: Change the autogenerated stub
    }
}
